version: '3'
services:
    # MYSQL
    db:
        build:
            context: .
            dockerfile: docker/mysql/Dockerfile
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        environment:
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: dbcode
        ports:
            - 3306:3306
        volumes:
            - ./db_data:/etc/mysql/conf.d

    # PHP with Apache2
    app:
        build:
            context: .
            dockerfile: docker/apache/Dockerfile
        volumes:
            - ./:/var/www/html/
        ports:
            - 80:80
        links:
            - db
        depends_on:
            - db
